#! /bin/sh

#
# This will run all tests for a simple compilation
#



# ---------------------------- Tests -----------------------------------

. threadpool
. pause_resume
. memleaks
. wait

echo "No errors"
