#! /bin/bash

#
# This file has several tests to check for memory leaks.
# valgrind is used so make sure you have it installed
#

. funcs


# ---------------------------- Tests -----------------------------------


function test_pause_resume_est7secs { #threads
	echo "Pause and resume test for 7 secs with $1 threads"
	gcc src/pause_resume.c ../thpool.c -pthread -o test
	realsecs=$(/usr/bin/time -f '%e' ./test "$1" 2>&1 > /dev/null)
	threshold=1.00 # in secs
	
	ret=$(python -c "print(($realsecs-7)<=$threshold)")

	if [ "$ret" == "True" ]; then
		return
	fi
	err "Elapsed $realsecs which is more than than allowed"
}



# Run tests
test_pause_resume_est7secs 4



echo "No pause/resume errors"
